### ISSUE TITLE
Failing build packages action

### ISSUE THREAD

**Issue by mburridge96** [iGEM-Engineering/iGEM-test-distribution-package#4]
Could not compute build plan for iGEM-test-distribution-package: An entity with identity "https://github.com/iGEM-Engineering/iGEM-test-distribution-package/Anderson_Promoters_in_vector_Anderson_Promoters_in_vector_ins_BBa_J23100" already exists in document

https://github.com/iGEM-Engineering/iGEM-test-distribution-package/blob/28a69073d02f7e5e223afacafcbfec4ddd9e5928/scripts/scriptutils/package_production.py#L133 Failing at this point

**Comment by jakebeal** [comment]
The problem appears be caused by the parts inventory collecting materials from the distributions files.
There are at least three potentials paths to fix this:
1. Skip the distributions files (simple, but kinda kludgey)
2. Put the distributions files in the views directory, along with the package files
3. Make the distributions files build artifacts, rather than committing them.

**Comment by jakebeal** [comment]
Following discussion, for now, we will go with option 2. In the future, we probably want to move to option 3.
